version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    restart: always
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "8000"]
